# Generated by Django 5.2.6 on 2025-10-27 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_filess_delete_files'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
