# Generated by Django 5.2.7 on 2025-10-30 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_user_alter_filess_user_delete_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='Users',
        ),
    ]
